ssvlabs/ssv-spec

- qbft/state_test.go
- qbft/testing_utils.go
- types/crypto_test.go
- types/domain.go
- types/signer.go
- types/spectest/all_tests.go
- types/testingutils/dkg.go
- types/testingutils/keymanager.go
- types/testingutils/qbft.go
- types/testingutils/qbft_msgs.go
- added DomainType for `shifu`
- added global domain to be used by other components
> Shifu Testnet Domain

- p2p/interface.go
- qbft/controller.go
- qbft/future_msg.go
- qbft/instance.go
- qbft/types.go
- ssv/types.go
- types/messages.go
- types/testingutils/network.go
**Changed**
- removed `BroadcastDecided()`
- generalized broadcaster interface
- syncer: changed to typed msg id
> Network Interface Alignment

- qbft/instance.go
- qbft/spectest/tests/controller_spectest.go
- types/testingutils/timer.go
Added a call for round timeout upon instance start.
> Reset round timer upon instance start

- qbft/round_change.go
- qbft/spectest/all_tests.go
- qbft/spectest/tests/controller_spectest.go
- qbft/spectest/tests/msg_processing_spectest.go
- qbft/spectest/tests/proposal/first_round_justification.go
- qbft/spectest/tests/proposal/future_round.go
- qbft/spectest/tests/proposal/future_round_prev_not_prepare.go
- qbft/spectest/tests/roundchange/f1_different_future_rounds.go
- qbft/spectest/tests/roundchange/f1_speedup.go
- qbft/spectest/tests/roundchange/happy_flow.go
- qbft/spectest/tests/roundchange/rc_partial_quorum.go
- qbft/spectest/tests/startinstance/first_height.go
- types/testingutils/timer.go
* reset timer in case we change round due to partial quorum
* added timer state assertions
* added test to check timer state on round change partial quorum
> Change Round: reset timer upon partial quorum

- dkg/spectest/all_tests.go
- qbft/round_change.go
- types/testingutils/qbft.go
> fixed non prepared rc value

- qbft/instance_test.go
- qbft/message_container_test.go
- qbft/round_robin_proposer_test.go
- qbft/state_test.go
- types/testingutils/ssv_msgs.go
Fix the import cycle in the qbft package by moving tests to the test_qbft package
> fix test import cycle & linting

- ssv/spectest/tests/messages/msg_signer_zero.go
- ssv/spectest/tests/messages/signed_msg_signer_zero.go
- ssv/spectest/tests/runner/consensus/future_decided.go
- ssv/spectest/tests/runner/consensus/invalid_decided_value.go
- ssv/spectest/tests/runner/consensus/past_msg.go
- ssv/spectest/tests/runner/consensus/post_decided.go
- ssv/spectest/tests/runner/consensus/post_finish.go
- ssv/spectest/tests/runner/consensus/valid_decided.go
- ssv/spectest/tests/runner/consensus/valid_decided_10_operators.go
- ssv/spectest/tests/runner/consensus/valid_decided_13_operators.go
- ssv/spectest/tests/runner/consensus/valid_decided_7_operators.go
- ssv/spectest/tests/runner/consensus/valid_message.go
- ssv/spectest/tests/runner/duties/newduty/consensus_not_started.go
- ssv/spectest/tests/runner/duties/newduty/finished.go
- ssv/spectest/tests/runner/duties/newduty/not_decided.go
- ssv/spectest/tests/runner/duties/newduty/post_future_decided.go
- ssv/spectest/tests/runner/duties/newduty/post_invalid_decided.go
- ssv/spectest/tests/runner/duties/newduty/post_wrong_decided.go
- ssv/spectest/tests/runner/duties/newduty/valid.go
Aligns  the following tests:
- messages
- runner consensus
- runner duties
> Version block support testing infra align tests 1

- ssv/spectest/tests/runner/duties/newduty/consensus_not_started.go
- ssv/spectest/tests/runner/duties/newduty/finished.go
- ssv/spectest/tests/runner/duties/newduty/not_decided.go
- ssv/spectest/tests/runner/duties/newduty/post_future_decided.go
- ssv/spectest/tests/runner/duties/newduty/post_invalid_decided.go
- ssv/spectest/tests/runner/duties/newduty/post_wrong_decided.go
- ssv/spectest/tests/runner/duties/newduty/valid.go
- ssv/spectest/tests/runner/duties/proposer/propose_blinded_decide_regular.go
- ssv/spectest/tests/runner/duties/proposer/propose_regular_decide_blinded.go
- ssv/spectest/tests/runner/full_happy_flow.go
- ssv/spectest/tests/runner/full_happy_flow_sc.go
Aligns the following tests:
- runner/full_happy_flow
- runner/postconsensus
> Version block support testing infra align tests 2

- ssv/spectest/tests/runner/postconsensus/duplicate_msg.go
- ssv/spectest/tests/runner/postconsensus/duplicate_msg_different_roots.go
- ssv/spectest/tests/runner/postconsensus/inconsistent_beacon_signer.go
- ssv/spectest/tests/runner/postconsensus/invalid_beacon_sig.go
- ssv/spectest/tests/runner/postconsensus/invalid_decided_value.go
- ssv/spectest/tests/runner/postconsensus/invalid_expected_root.go
- ssv/spectest/tests/runner/postconsensus/invalid_msg.go
- ssv/spectest/tests/runner/postconsensus/invalid_msg_sig.go
- ssv/spectest/tests/runner/postconsensus/no_running_duty.go
- ssv/spectest/tests/runner/postconsensus/post_finish.go
- ssv/spectest/tests/runner/postconsensus/post_quorum.go
- ssv/spectest/tests/runner/postconsensus/pre_decided.go
- ssv/spectest/tests/runner/postconsensus/quorum.go
- ssv/spectest/tests/runner/postconsensus/quorum_10_operators.go
- ssv/spectest/tests/runner/postconsensus/quorum_13_operators.go
- ssv/spectest/tests/runner/postconsensus/quorum_7_operators.go
- ssv/spectest/tests/runner/postconsensus/unknown_signer.go
- ssv/spectest/tests/runner/postconsensus/unordered_expected_roots.go
- ssv/spectest/tests/runner/postconsensus/valid_msg.go
- ssv/spectest/tests/runner/postconsensus/valid_msg_10_operators.go
- ssv/spectest/tests/runner/postconsensus/valid_msg_13_operators.go
- ssv/spectest/tests/runner/postconsensus/valid_msg_7_operators.go
Aligns  the following tests:
- runner/postconsensus
> Version block support testing infra align tests 3

- ssv/spectest/tests/runner/pre_consensus_justifications/decided_instance.go
- ssv/spectest/tests/runner/pre_consensus_justifications/duplicate_justification_signer.go
- ssv/spectest/tests/runner/pre_consensus_justifications/duplicate_roots.go
- ssv/spectest/tests/runner/pre_consensus_justifications/existing_valid_pre_consensus.go
- ssv/spectest/tests/runner/pre_consensus_justifications/future_height.go
- ssv/spectest/tests/runner/pre_consensus_justifications/happy_flow.go
- ssv/spectest/tests/runner/pre_consensus_justifications/inconsisten_root_count.go
- ssv/spectest/tests/runner/pre_consensus_justifications/inconsisten_roots.go
- ssv/spectest/tests/runner/pre_consensus_justifications/invalid_consensus_data.go
- ssv/spectest/tests/runner/pre_consensus_justifications/invalid_data.go
- ssv/spectest/tests/runner/pre_consensus_justifications/invalid_justification.go
- ssv/spectest/tests/runner/pre_consensus_justifications/invalid_justification_sig.go
- ssv/spectest/tests/runner/pre_consensus_justifications/invalid_msg_type.go
- ssv/spectest/tests/runner/pre_consensus_justifications/missing_quorum.go
- ssv/spectest/tests/runner/pre_consensus_justifications/past_height.go
- ssv/spectest/tests/runner/pre_consensus_justifications/past_slot.go
- ssv/spectest/tests/runner/pre_consensus_justifications/unknow_siger.go
- ssv/spectest/tests/runner/pre_consensus_justifications/valid.go
- ssv/spectest/tests/runner/pre_consensus_justifications/valid_10_operators.go
- ssv/spectest/tests/runner/pre_consensus_justifications/valid_13_operators.go
- ssv/spectest/tests/runner/pre_consensus_justifications/valid_7_operators.go
- ssv/spectest/tests/runner/pre_consensus_justifications/valid_first_height.go
- ssv/spectest/tests/runner/pre_consensus_justifications/valid_no_duty_runnnig.go
- ssv/spectest/tests/runner/pre_consensus_justifications/valid_round_change_msg.go
- ssv/spectest/tests/runner/pre_consensus_justifications/wrong_beacon_role.go
Aligns  the following tests:
- runner/pre_consensus_justifications
> Version block support testing infra align tests 4

- ssv/spectest/tests/runner/preconsensus/duplicate_msg.go
- ssv/spectest/tests/runner/preconsensus/duplicate_msg_different_roots.go
- ssv/spectest/tests/runner/preconsensus/inconsistent_beacon_signer.go
- ssv/spectest/tests/runner/preconsensus/invalid_msg_sig.go
- ssv/spectest/tests/runner/preconsensus/invalid_msg_slot.go
- ssv/spectest/tests/runner/preconsensus/invalid_signed_msg.go
- ssv/spectest/tests/runner/preconsensus/no_running_duty.go
- ssv/spectest/tests/runner/preconsensus/post_decided.go
- ssv/spectest/tests/runner/preconsensus/post_finish.go
- ssv/spectest/tests/runner/preconsensus/post_quorum.go
- ssv/spectest/tests/runner/preconsensus/quorum.go
- ssv/spectest/tests/runner/preconsensus/quorum_10_operators.go
- ssv/spectest/tests/runner/preconsensus/quorum_13_operators.go
- ssv/spectest/tests/runner/preconsensus/quorum_7_operators.go
- ssv/spectest/tests/runner/preconsensus/unknown_signer.go
- ssv/spectest/tests/runner/preconsensus/unordered_expected_roots.go
- ssv/spectest/tests/runner/preconsensus/valid_msg.go
- ssv/spectest/tests/runner/preconsensus/valid_msg_10_operators.go
- ssv/spectest/tests/runner/preconsensus/valid_msg_13_operators.go
- ssv/spectest/tests/runner/preconsensus/valid_msg_7_operators.go
Aligns versioned runner/preconsensus
> Version block support testing infra align tests 5

- ssv/spectest/tests/valcheck/valcheckduty/far_future_duty_slot.go
- ssv/spectest/tests/valcheck/valcheckduty/wrong_duty_type.go
- ssv/spectest/tests/valcheck/valcheckduty/wrong_validator_index.go
- ssv/spectest/tests/valcheck/valcheckduty/wrong_validator_pk.go
- types/spectest/tests/consensusdata/proposer/versioned_blinded_block_consensus_data_nil.go
- types/spectest/tests/consensusdata/proposer/versioned_blinded_block_unknown_version.go
- types/spectest/tests/consensusdata/proposer/versioned_blinded_block_validation.go
- types/spectest/tests/consensusdata/proposer/versioned_block_consensus_data_nil.go
- types/spectest/tests/consensusdata/proposer/versioned_block_unknown_version.go
- types/spectest/tests/consensusdata/proposer/versioned_block_validation.go
- types/testingutils/beacon_node_test.go
Aligns the following tests:
1. beacon_node_test
2.  consensusdata/proposer
3. valcheck/valcheckduty
> Version block support testing infra align tests 6

- types/testingutils/beacon_node.go
- types/testingutils/runner.go
- types/testingutils/ssv_msgs.go
> Remove non-versioned functions

- ssv/spectest/run_test.go
This pull request (PR) addresses a deadlock issue in the SSV JSON spectest. The deadlock bug is resolved, ensuring smooth and uninterrupted execution of the spectest.
> SSV JSON spectest deadlock fix

- ssv/spectest/tests/runner/duties/newduty/valid.go
`tests.json` needs the tests to have hardcoded roots
> add missing roots

- ssv/runner.go
- ssv/spectest/all_tests.go
- ssv/spectest/generate/state_comparison/newduty_MultiStartNewRunnerDutySpecTest/new_duty_first_height/aggregator.json
- ssv/spectest/generate/state_comparison/newduty_MultiStartNewRunnerDutySpecTest/new_duty_first_height/attester.json
- ssv/spectest/generate/state_comparison/newduty_MultiStartNewRunnerDutySpecTest/new_duty_first_height/proposer.json
- ssv/spectest/generate/state_comparison/newduty_MultiStartNewRunnerDutySpecTest/new_duty_first_height/sync committee aggregator.json
- ssv/spectest/generate/state_comparison/newduty_MultiStartNewRunnerDutySpecTest/new_duty_first_height/sync committee.json
- ssv/spectest/run_test.go
- ssv/spectest/tests/runner/duties/newduty/first_height.go
- types/testingutils/beacon_node.go
Allows to process duties that start at slot 0
> Spec - Consider first height in should process duty

- p2p/CONFIG.md
Dout is now 4 for better eclipse protection
> Add Dout to Config.MD

- types/domain_type.go
Add a new Domain to Prepare for the fork
> Alan Domain

- types/generate.go
> up go-eth2-client

- ssv/aggregator.go
- ssv/committee_runner.go
- ssv/pre_consensus_justification.go
- ssv/proposer.go
- ssv/runner.go
- ssv/sync_committee_aggregator.go
Use `Encoder` interface when calling `decide`
> use encoder interface
