Makefile
Go's default timeout for tests is 10 min, increasing as our tests usually takes more time.
=> CI: extend tests timeout to 20min

qbft/instance.go, qbft/types.go, types/testingutils/network.go
In https://github.com/bloxapp/ssv/pull/756, `SyncHighestRoundChange` became not used anymore but its implementation is still kept to match the `Syncer` interface (https://github.com/bloxapp/ssv/blob/spec-align-qbft/network/p2p/p2p_sync.go#L49). 
The goal of this PR is to get rid of the `SyncHighestRoundChange` implementation.
=> qbft/ remove SyncHighestRoundChange from Syncer interface

qbft/instance.go, qbft/round_change.go, qbft/spectest/tests/commit/past_round.go, qbft/spectest/tests/controller/latemsg/late_commit_past_round.go, qbft/spectest/tests/controller/latemsg/late_prepare_past_round.go, qbft/spectest/tests/controller/latemsg/late_proposal_past_round.go, qbft/spectest/tests/controller/latemsg/late_round_change_past_round.go, qbft/spectest/tests/prepare/old_round.go, qbft/spectest/tests/proposal/past_round_prev_not_prepared.go, qbft/spectest/tests/proposal/past_round_prev_prepared.go, qbft/spectest/tests/roundchange/justification_past_round.go, qbft/spectest/tests/roundchange/past_round.go
Fail base msg validation (instance) in case we notice a message with past round, before doing a more extensive validation.
=> qbft/ Round validation for consensus messages

ssv/runner_signatures.go, ssv/spectest/tests/runner/preconsensus/valid_msg.go, types/signer.go, types/testingutils/beacon_node.go, types/testingutils/keymanager.go, types/testingutils/ssv_msgs.go
Pass domain type to SignBeaconObject func instead of the role
the bug:
- passing the beacon role type to the SignBeaconObject function misleads the dynamic check for slashing protection.
e.g. passing BNRoleProposer for Randao
=> Slashing protection Fix

qbft/decided.go, qbft/proposal.go, qbft/round_change.go
In all cases of `errors.Wrap(err, "H(data) != root")` `err` is always `nil` (the result of `HashDataRoot`), so `errors.Wrap` always returns `nil` according to https://pkg.go.dev/github.com/pkg/errors#Wrap
=> Fix checks if H(data) != root

qbft/types.go
Signature for `SyncDecidedByRange` was `to, from`, but it's being called with `from, to`:
https://github.com/bloxapp/ssv-spec/blob/d3d9ae83654c9cf7f38a3bf4969c9225f20a0c48/qbft/decided.go#L49
=> Swap `(to, from)` -> `(from, to)` in `SyncDecidedByRange`

types/testingutils/ssv_msgs.go
Since SSZ validates the data before encoding, it can return errors where JSON wouldn't have.
For example, I spent an hour not realizing why tests fail, and finally found out that we were ignoring an encoding error:
```
SignedMessage.Signature (bytes array does not have the correct length): expected 96 and 4 found
```
This PR just panics instead of returns because these errors should only happen when editing/writing tests.
=> testingutils: don't ignore encoding errors

qbft/generate.go, types/generate.go
So one can generate jsons from any device
=> Use full path for ssz

types/testingutils/ssv_msgs.go
The util function should do only one thing, and use a different signer ID w.o tinkering with the sig itself
=> No need to switch wrong sig when you tinker with signer id

qbft/spectest/tests/controller_spectest.go, ssv/spectest/tests/msg_processing_spectest.go, ssv/spectest/tests/runner/duties/newduty/test.go, ssv/spectest/tests/runner/duties/synccommitteeaggregator/proof_spectest.go
Backwards compatibility makes amending the spec ridiculously slow.
So we remove it. 
When we see a test that still has a root in the json, we know it wasn't still properly vetted
=> Remove backwards compatibility for state comparison

types/testingutils/comparable/helpers.go
When generating jsons don't change characters of the base dir, because it may change the base location of the files
=> Meta: Don't change characters in base dir when generating jsons

ssv/runner.go, ssv/spectest/generate/state_comparison/newduty_MultiStartNewRunnerDutySpecTest/duplicate_duty_finished/validator registration.json, ssv/spectest/generate/state_comparison/newduty_MultiStartNewRunnerDutySpecTest/duplicate_duty_finished/voluntary exit.json, ssv/spectest/generate/state_comparison/newduty_MultiStartNewRunnerDutySpecTest/new_duty_consensus_not_started/validator registration.json, ssv/spectest/generate/state_comparison/newduty_MultiStartNewRunnerDutySpecTest/new_duty_consensus_not_started/voluntary exit.json, ssv/spectest/generate/state_comparison/newduty_MultiStartNewRunnerDutySpecTest/new_duty_finished/validator registration.json, ssv/spectest/generate/state_comparison/newduty_MultiStartNewRunnerDutySpecTest/new_duty_finished/voluntary exit.json, ssv/spectest/run_test.go, ssv/spectest/tests/runner/duties/newduty/consensus_not_started.go, ssv/spectest/tests/runner/duties/newduty/duplicate_duty_finished.go, ssv/spectest/tests/runner/duties/newduty/duplicate_duty_not_finished.go, ssv/spectest/tests/runner/duties/newduty/finished.go, ssv/validator_registration.go, ssv/voluntary_exit.go, types/testingutils/beacon_node.go, types/testingutils/ssv_msgs.go
Stalling ValidatorRegistration/ValidatorExit duties prevented the execution of new duties. Now when a duty that fits a higher slot comes in it stops the old one.
Added missing cases to:
`consensus_not_started`, `duplicate_duty_finished`, `duplicate_duty_not_finished`, and `finished`.
=> Spec - Validator registration and voluntary exit now stop old duties

qbft/messages.go
Closes #320
Add comments to `DataRound` so it will be clear why `RoundChangePrepared()`  works as intended
=> Clarify `DataRound` with comment

ssv/runner.go, ssv/spectest/all_tests.go, ssv/spectest/generate/state_comparison/tests_MultiMsgProcessingSpecTest/consensus_future_decided_no_running_instance/aggregator.json, ssv/spectest/generate/state_comparison/tests_MultiMsgProcessingSpecTest/consensus_future_decided_no_running_instance/attester.json, ssv/spectest/generate/state_comparison/tests_MultiMsgProcessingSpecTest/consensus_future_decided_no_running_instance/proposer (bellatrix).json, ssv/spectest/generate/state_comparison/tests_MultiMsgProcessingSpecTest/consensus_future_decided_no_running_instance/proposer (capella).json, ssv/spectest/generate/state_comparison/tests_MultiMsgProcessingSpecTest/consensus_future_decided_no_running_instance/proposer (deneb).json, ssv/spectest/generate/state_comparison/tests_MultiMsgProcessingSpecTest/consensus_future_decided_no_running_instance/proposer blinded block (bellatrix).json, ssv/spectest/generate/state_comparison/tests_MultiMsgProcessingSpecTest/consensus_future_decided_no_running_instance/proposer blinded block (capella).json, ssv/spectest/generate/state_comparison/tests_MultiMsgProcessingSpecTest/consensus_future_decided_no_running_instance/proposer blinded block (deneb).json, ssv/spectest/generate/state_comparison/tests_MultiMsgProcessingSpecTest/consensus_future_decided_no_running_instance/sync committee contribution.json, ssv/spectest/generate/state_comparison/tests_MultiMsgProcessingSpecTest/consensus_future_decided_no_running_instance/sync committee.json, ssv/spectest/tests/runner/consensus/future_decided_no_instance.go
Fix https://github.com/bloxapp/ssv-spec/issues/235 by adding a `nil` check.
New test:
=> Fix - Future decided no instance nil check

types/testingutils/keymanager.go
The purpose of this PR is to optimize the performance of test generation and execution with the purpose of improving work quality on future changes.
The `ssv` module is the one that takes the most time. After running a CPU profiling test, we noticed that the `NewTestingKeyManager` function consumes 80% of the total time, which is explained by the fact that it's called multiple times and takes 26 milliseconds to run (according to benchmark tests).
Nonetheless, the `NewTestingKeyManager` function returns a `testingKeyManager` object that is only used to validate and sign data but does not change state throughout a test execution. Thus, we propose adding a singleton pattern for this object.
To illustrate the number of times the `NewTestingKeyManager` function is called, take a look at the …
=> Improve performance for test generation and execution

p2p/interface.go, qbft/controller.go, qbft/instance.go, ssv/aggregator.go, ssv/attester.go, ssv/proposer.go, ssv/sync_committee.go, ssv/sync_committee_aggregator.go, ssv/validator_registration.go, ssv/voluntary_exit.go, types/messages.go, types/testingutils/network.go
This PR is a follow up for https://github.com/bloxapp/ssv-spec/pull/372.
- Pass message ID to broadcast
=> Pass MessageID To Broadcast

types/messages.go
1. `MessageIDFromBytes` isn't used by spec code so it was removed
2. Also refactored order of parameters so it is clearer (no logic change)
=> Remove needless constructor

ssv/committee_runner.go
Calculating MsgIDs from a single share in committee runner is conceptually wrong.
In the `ProcessConsensus` function we can can get the needed info out of QBFTController
=> Use domain from controller

p2p/validation/msg_validation.go, qbft/commit.go, qbft/decided.go, qbft/message_container.go, qbft/messages.go, qbft/prepare.go, qbft/proposal.go, qbft/round_change.go, qbft/spectest/tests/controller_spectest.go, qbft/state_test.go, ssv/aggregator.go, ssv/committee_runner.go, ssv/proposer.go, ssv/sync_committee_aggregator.go, ssv/validator_registration.go, ssv/voluntary_exit.go, types/consensus_data.go, types/messages.go, types/partial_sig_message.go, types/spectest/tests/committeemember/test.go, types/spectest/tests/share/test.go
This PR removes the following convenience functions:
- `CreateValidatorConsensusData`
- `SSVMessageToSignedSSVMessage`
- `PartialSignatureMessagesToSignedSSVMessage`
- `NewBeaconVote`
and the redundant `SignedSSVMessage.GetOperatorID` function.
=> Remove convenience functions

ssv/partial_sig_container.go, ssv/runner.go
This PR performs two changes:
1. Uses `PartialSigContainer.GetSignature` in `PartialSigContainer.HasSigner` to avoid duplication code.
2. Renames `PartialSigContainer.HasSigner` to `PartialSigContainer.HasSignature`, since we're actually looking for the existence (or not) of a signature.
=> Refactor PartialSigContainer.HasSigner: avoid duplication code and rename

ssv/runner.go
This PR simply fixes the name of the `RunnerRoleType` argument in `NewBaseRunner`, since it used the deprecated field name (`beaconRoleType`).
=> Fix RunnerRoleType argument name in NewBaseRunner

ssv/partial_sig_container.go, ssv/spectest/comparable/messages.go
This PR improves the readability of the `Signatures` map field of the `PartialSigContainer` structure.
In the map definition, instead of `string`, it uses a new `SigningRoot` type, and, instead of `[]byte`, it uses the existing `types.Signature` type.
=> Use naming in complex nested map

ssv/spectest/all_tests.go, ssv/spectest/tests/msg_processing_spectest.go, ssv/spectest/tests/valcheck/test.go, ssv/spectest/tests/valcheck/valcheckattestations/attestation_data_nil.go, ssv/spectest/tests/valcheck/valcheckattestations/far_future_target.go, ssv/spectest/tests/valcheck/valcheckattestations/majority_slashable.go, ssv/spectest/tests/valcheck/valcheckattestations/minority_slashable.go, ssv/spectest/tests/valcheck/valcheckattestations/slashable.go, ssv/spectest/tests/valcheck/valcheckattestations/source_higher_than_target.go, ssv/spectest/tests/valcheck/valcheckattestations/valid.go, ssv/spectest/tests/valcheck/valcheckattestations/valid_non_slashable_slot.go, types/testingutils/keymanager.go
This PR modifies the `TestingKeyManager` to do the slashing check based on the slot, instead of the data root.
=> TestingKeyManager: Slashing by Slot

types/testingutils/compare.go
This PR fixes the issue with `CompareSignedSSVMessageOutputMessages` and simplifies comparison methods.
For the `CompareSignedSSVMessageOutputMessages` function, it implements the requirement that:
- the broadcasted and expected messages have equal length
- every broadcasted message is linked (equal) to an expected message
- two broadcasted messages are not linked to the same expected message
i.e. a bijection between the lists.
=> Simplify comparison methods

ssv/committee_runner.go
We have notice in the node attempts to send empty duties. calling `SubmitSyncCommitteeMessages` with empty data, resulting in an error.
Check that there is any duty before calling send.
=> fix: check att and sync duties exist before submitting

qbft/spectest/generate/main.go, qbft/spectest/tests/controller_spectest.go, ssv/runner_validations.go, ssv/spectest/generate/main.go, types/spectest/generate/main.go, types/testingutils/comparable/helpers.go, types/testingutils/shuffle.go
This PR adds fixes for static analysis issues including:
- file permission issues
- file inclusion via variable issues
It also adds a `nosec` comment for a cryptographically insecure PRNG (pseudo-random number generator) used in tests. We use this PRNG (`math/rand`) since the secure `crypto/rand` doesn't allow seeding (which is important for consistent tests).
An existing issue with implicit memory aliasing in a for loop will be automatically fixed by the go update to 1.22.
=> Fix static analysis issues

qbft/instance.go, qbft/timeout.go, ssv/runner_validations.go, ssv/spectest/tests/runner/duties/newduty/consensus_not_started.go, ssv/spectest/tests/runner/duties/newduty/finished.go, ssv/spectest/tests/runner/duties/newduty/not_decided.go, ssv/spectest/tests/runner/duties/newduty/post_future_decided.go, ssv/spectest/tests/runner/preconsensus/post_decided.go, ssv/spectest/tests/runner/preconsensus/post_finish.go
This PR drops unnecessary `nolint` comments.
There were lint errors related to the unused variables `quickTimeoutThreshold`, `quickTimeout` and `slowTimeout` in `timeout.go`. To resolve these errors while preserving their intended use as informative constants for implementation, these variables have been capitalised to make them exported (accessible outside their package), avoiding the lint errors.
Note: There are still `nolint` comments in `encryption.go` but the related function will be fixed in another PR.
=> Drop unnecessary nolint comments

ssv/runner_validations.go, types/encryption.go
This PR adjusts the `PemToPrivateKey` and `PemToPublicKey` functions to use a secure storage method, removing the deprecated functions that were being used.
=> Secure key storage

.gitignore, qbft/spectest/generate/main.go, ssv/spectest/generate/main.go, types/spectest/generate/main.go
After recent change in spec, we need to run `go generate` to get tests.json file used for testing in ssv. But because of `runtime.Caller(0)` generating json outside the repo is impossible. Whit this proposed change we can run it in any directory, where the binary used for generating code is located
=> fix json generation

.github/workflows/stale.yml
Implements a GitHub Actions workflow that automatically labels pull requests and issues as stale after 60 days of inactivity.
It will post a message and apply a 'stale' label.
The workflow runs daily and can be manually triggered.
=> Adds stale PR and issue labeling workflow
